# Generated by Django 5.0.4 on 2024-05-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0003_alter_search_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='data_from',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
