# Generated by Django 4.2.13 on 2024-10-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0005_remove_search_data_from_remove_search_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='products_from_lidl',
            field=models.TextField(blank=True),
        ),
    ]
