# Generated by Django 4.2.13 on 2024-10-29 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0006_search_products_from_lidl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('img_src', models.CharField(blank=True, max_length=200, null=True)),
                ('img_srcset', models.CharField(blank=True, max_length=500, null=True)),
                ('price', models.FloatField(blank=True)),
                ('product_from', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.RemoveField(
            model_name='search',
            name='products_from_aldi',
        ),
        migrations.RemoveField(
            model_name='search',
            name='products_from_coop',
        ),
        migrations.RemoveField(
            model_name='search',
            name='products_from_lidl',
        ),
        migrations.RemoveField(
            model_name='search',
            name='products_from_migros',
        ),
        migrations.AddField(
            model_name='product',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='scrap.search'),
        ),
    ]
