# Generated by Django 4.2.13 on 2024-11-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0008_rename_query_product_search_alter_product_img_src_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='query',
            field=models.CharField(max_length=120, unique=True, verbose_name='Query'),
        ),
    ]
